mkdir -p '100-man no Inochi no Ue ni Ore wa Tatte Iru'
mv torrents/'[Erai-raws] 100-man no Inochi no Ue ni Ore wa Tatte Iru - 04 [1080p][Multiple Subtitle].mkv' '100-man no Inochi no Ue ni Ore wa Tatte Iru'/'[Erai-raws] 100-man no Inochi no Ue ni Ore wa Tatte Iru - 04 [1080p][Multiple Subtitle].mkv'
mkdir -p 'A3! Season Autumn and Winter'
mv torrents/'[Erai-raws] A3! Season Autumn and Winter - 02 [v0][1080p].mkv' 'A3! Season Autumn and Winter'/'[Erai-raws] A3! Season Autumn and Winter - 02 [v0][1080p].mkv'
mkdir -p 'Akudama Drive'
mv torrents/'[Erai-raws] Akudama Drive - 03 [1080p].mkv' 'Akudama Drive'/'[Erai-raws] Akudama Drive - 03 [1080p].mkv'
mkdir -p 'Assault Lily - Bouquet'
mv torrents/'[Erai-raws] Assault Lily - Bouquet - 04 [1080p].mkv' 'Assault Lily - Bouquet'/'[Erai-raws] Assault Lily - Bouquet - 04 [1080p].mkv'
mkdir -p 'Assault Lily - Bouquet'
mv torrents/'[Erai-raws] Assault Lily - Bouquet - 04 [v0][1080p].mkv' 'Assault Lily - Bouquet'/'[Erai-raws] Assault Lily - Bouquet - 04 [v0][1080p].mkv'
mkdir -p 'Detective Conan'
mv torrents/'[Erai-raws] Detective Conan - 985 [1080p].mkv' 'Detective Conan'/'[Erai-raws] Detective Conan - 985 [1080p].mkv'
mkdir -p 'Digimon Adventure (2020)'
mv torrents/'[Erai-raws] Digimon Adventure (2020) - 21 [1080p][Multiple Subtitle].mkv' 'Digimon Adventure (2020)'/'[Erai-raws] Digimon Adventure (2020) - 21 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Dragon Quest - Dai no Daibouken (2020)'
mv torrents/'[Erai-raws] Dragon Quest - Dai no Daibouken (2020) - 04 [1080p][Multiple Subtitle].mkv' 'Dragon Quest - Dai no Daibouken (2020)'/'[Erai-raws] Dragon Quest - Dai no Daibouken (2020) - 04 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III'
mv torrents/'[Erai-raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III - 01 [VRV][1080p][Multiple Subtitle].mkv' 'Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III'/'[Erai-raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III - 01 [VRV][1080p][Multiple Subtitle].mkv'
mkdir -p 'Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III'
mv torrents/'[Erai-raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III - 02 [VRV][1080p][Multiple Subtitle].mkv' 'Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III'/'[Erai-raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III - 02 [VRV][1080p][Multiple Subtitle].mkv'
mkdir -p 'Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III'
mv torrents/'[Erai-raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III - 03 [VRV][1080p][Multiple Subtitle].mkv' 'Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III'/'[Erai-raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III - 03 [VRV][1080p][Multiple Subtitle].mkv'
mkdir -p 'Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III'
mv torrents/'[Erai-raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III - 04 [1080p][Multiple Subtitle].mkv' 'Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III'/'[Erai-raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III - 04 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III'
mv torrents/'[Erai-raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III - 04 [VRV][1080p][Multiple Subtitle].mkv' 'Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III'/'[Erai-raws] Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III - 04 [VRV][1080p][Multiple Subtitle].mkv'
mkdir -p 'Enen no Shouboutai - Ni no Shou'
mv torrents/'[Erai-raws] Enen no Shouboutai - Ni no Shou - 17 [1080p].mkv' 'Enen no Shouboutai - Ni no Shou'/'[Erai-raws] Enen no Shouboutai - Ni no Shou - 17 [1080p].mkv'
mkdir -p 'Enen no Shouboutai - Ni no Shou'
mv torrents/'[Erai-raws] Enen no Shouboutai - Ni no Shou - 17 [1080p][Multiple Subtitle].mkv' 'Enen no Shouboutai - Ni no Shou'/'[Erai-raws] Enen no Shouboutai - Ni no Shou - 17 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Gochuumon wa Usagi Desuka Bloom'
mv torrents/'[Erai-raws] Gochuumon wa Usagi Desuka Bloom - 01 [VRV][1080p][Multiple Subtitle].mkv' 'Gochuumon wa Usagi Desuka Bloom'/'[Erai-raws] Gochuumon wa Usagi Desuka Bloom - 01 [VRV][1080p][Multiple Subtitle].mkv'
mkdir -p 'Gochuumon wa Usagi Desuka Bloom'
mv torrents/'[Erai-raws] Gochuumon wa Usagi Desuka Bloom - 02 [VRV][1080p][Multiple Subtitle].mkv' 'Gochuumon wa Usagi Desuka Bloom'/'[Erai-raws] Gochuumon wa Usagi Desuka Bloom - 02 [VRV][1080p][Multiple Subtitle].mkv'
mkdir -p 'Gochuumon wa Usagi Desuka Bloom'
mv torrents/'[Erai-raws] Gochuumon wa Usagi Desuka Bloom - 03 [VRV][1080p][Multiple Subtitle].mkv' 'Gochuumon wa Usagi Desuka Bloom'/'[Erai-raws] Gochuumon wa Usagi Desuka Bloom - 03 [VRV][1080p][Multiple Subtitle].mkv'
mkdir -p 'Hanyou no Yashahime - Sengoku Otogizoushi'
mv torrents/'[Erai-raws] Hanyou no Yashahime - Sengoku Otogizoushi - 04 [1080p][Multiple Subtitle].mkv' 'Hanyou no Yashahime - Sengoku Otogizoushi'/'[Erai-raws] Hanyou no Yashahime - Sengoku Otogizoushi - 04 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Healin Good Precure'
mv torrents/'[Erai-raws] Healin Good Precure - 30 [1080p][Multiple Subtitle].mkv' 'Healin Good Precure'/'[Erai-raws] Healin Good Precure - 30 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Himitsukessha Taka no Tsume - Golden Spell'
mv torrents/'[Erai-raws] Himitsukessha Taka no Tsume - Golden Spell - 01 [1080p][Multiple Subtitle].mkv' 'Himitsukessha Taka no Tsume - Golden Spell'/'[Erai-raws] Himitsukessha Taka no Tsume - Golden Spell - 01 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Himitsukessha Taka no Tsume - Golden Spell'
mv torrents/'[Erai-raws] Himitsukessha Taka no Tsume - Golden Spell - 02 [1080p][Multiple Subtitle].mkv' 'Himitsukessha Taka no Tsume - Golden Spell'/'[Erai-raws] Himitsukessha Taka no Tsume - Golden Spell - 02 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Himitsukessha Taka no Tsume - Golden Spell'
mv torrents/'[Erai-raws] Himitsukessha Taka no Tsume - Golden Spell - 03 [1080p][Multiple Subtitle].mkv' 'Himitsukessha Taka no Tsume - Golden Spell'/'[Erai-raws] Himitsukessha Taka no Tsume - Golden Spell - 03 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Himitsukessha Taka no Tsume - Golden Spell'
mv torrents/'[Erai-raws] Himitsukessha Taka no Tsume - Golden Spell - 04 [1080p][Multiple Subtitle].mkv' 'Himitsukessha Taka no Tsume - Golden Spell'/'[Erai-raws] Himitsukessha Taka no Tsume - Golden Spell - 04 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Hypnosis Mic - Division Rap Battle - Rhyme Anima'
mv torrents/'[Erai-raws] Hypnosis Mic - Division Rap Battle - Rhyme Anima - 04 [1080p].mkv' 'Hypnosis Mic - Division Rap Battle - Rhyme Anima'/'[Erai-raws] Hypnosis Mic - Division Rap Battle - Rhyme Anima - 04 [1080p].mkv'
mkdir -p 'Hypnosis Mic - Division Rap Battle - Rhyme Anima'
mv torrents/'[Erai-raws] Hypnosis Mic - Division Rap Battle - Rhyme Anima - 04 [v0][1080p].mkv' 'Hypnosis Mic - Division Rap Battle - Rhyme Anima'/'[Erai-raws] Hypnosis Mic - Division Rap Battle - Rhyme Anima - 04 [v0][1080p].mkv'
mkdir -p 'IDOLiSH7 - Second Beat!'
mv torrents/'[Erai-raws] IDOLiSH7 - Second Beat! - 06 [1080p][Multiple Subtitle].mkv' 'IDOLiSH7 - Second Beat!'/'[Erai-raws] IDOLiSH7 - Second Beat! - 06 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Inu to Neko Docchi mo Katteru to Mainichi Tanoshii'
mv torrents/'[Erai-raws] Inu to Neko Docchi mo Katteru to Mainichi Tanoshii - 04 [1080p][Multiple Subtitle].mkv' 'Inu to Neko Docchi mo Katteru to Mainichi Tanoshii'/'[Erai-raws] Inu to Neko Docchi mo Katteru to Mainichi Tanoshii - 04 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Iwa Kakeru! Sport Climbing Girls'
mv torrents/'[Erai-raws] Iwa Kakeru! Sport Climbing Girls - 04 [1080p][Multiple Subtitle].mkv' 'Iwa Kakeru! Sport Climbing Girls'/'[Erai-raws] Iwa Kakeru! Sport Climbing Girls - 04 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Jujutsu Kaisen'
mv torrents/'[Erai-raws] Jujutsu Kaisen - 04 [1080p][Multiple Subtitle].mkv' 'Jujutsu Kaisen'/'[Erai-raws] Jujutsu Kaisen - 04 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Kami-tachi ni Hirowareta Otoko'
mv torrents/'[Erai-raws] Kami-tachi ni Hirowareta Otoko - 04 [v0][1080p].mkv' 'Kami-tachi ni Hirowareta Otoko'/'[Erai-raws] Kami-tachi ni Hirowareta Otoko - 04 [v0][1080p].mkv'
mkdir -p 'Kamisama ni Natta Hi'
mv torrents/'[Erai-raws] Kamisama ni Natta Hi - 03 [v0][1080p].mkv' 'Kamisama ni Natta Hi'/'[Erai-raws] Kamisama ni Natta Hi - 03 [v0][1080p].mkv'
mkdir -p "King's Raid - Ishi o Tsugu Mono-tachi"
mv torrents/"[Erai-raws] King's Raid - Ishi o Tsugu Mono-tachi - 04 [1080p].mkv" "King's Raid - Ishi o Tsugu Mono-tachi"/"[Erai-raws] King's Raid - Ishi o Tsugu Mono-tachi - 04 [1080p].mkv"
mkdir -p "King's Raid - Ishi o Tsugu Mono-tachi"
mv torrents/"[Erai-raws] King's Raid - Ishi o Tsugu Mono-tachi - 04 [v0][1080p].mkv" "King's Raid - Ishi o Tsugu Mono-tachi"/"[Erai-raws] King's Raid - Ishi o Tsugu Mono-tachi - 04 [v0][1080p].mkv"
mkdir -p 'Love Live! Nijigasaki Gakuen School Idol Doukoukai'
mv torrents/'[Erai-raws] Love Live! Nijigasaki Gakuen School Idol Doukoukai - 01 [1080p][Multiple Subtitle].mkv' 'Love Live! Nijigasaki Gakuen School Idol Doukoukai'/'[Erai-raws] Love Live! Nijigasaki Gakuen School Idol Doukoukai - 01 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Love Live! Nijigasaki Gakuen School Idol Doukoukai'
mv torrents/'[Erai-raws] Love Live! Nijigasaki Gakuen School Idol Doukoukai - 02 [1080p][Multiple Subtitle].mkv' 'Love Live! Nijigasaki Gakuen School Idol Doukoukai'/'[Erai-raws] Love Live! Nijigasaki Gakuen School Idol Doukoukai - 02 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Love Live! Nijigasaki Gakuen School Idol Doukoukai'
mv torrents/'[Erai-raws] Love Live! Nijigasaki Gakuen School Idol Doukoukai - 03 [1080p][Multiple Subtitle].mkv' 'Love Live! Nijigasaki Gakuen School Idol Doukoukai'/'[Erai-raws] Love Live! Nijigasaki Gakuen School Idol Doukoukai - 03 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Love Live! Nijigasaki Gakuen School Idol Doukoukai'
mv torrents/'[Erai-raws] Love Live! Nijigasaki Gakuen School Idol Doukoukai - 04 [1080p][Multiple Subtitle].mkv' 'Love Live! Nijigasaki Gakuen School Idol Doukoukai'/'[Erai-raws] Love Live! Nijigasaki Gakuen School Idol Doukoukai - 04 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Love Live! Nijigasaki Gakuen School Idol Doukoukai'
mv torrents/'[Erai-raws] Love Live! Nijigasaki Gakuen School Idol Doukoukai - 04 [v0][1080p].mkv' 'Love Live! Nijigasaki Gakuen School Idol Doukoukai'/'[Erai-raws] Love Live! Nijigasaki Gakuen School Idol Doukoukai - 04 [v0][1080p].mkv'
mkdir -p 'Maesetsu! Opening Act'
mv torrents/'[Erai-raws] Maesetsu! Opening Act - 03 [v0][1080p].mkv' 'Maesetsu! Opening Act'/'[Erai-raws] Maesetsu! Opening Act - 03 [v0][1080p].mkv'
mkdir -p 'Mahouka Koukou no Rettousei - Raihousha Hen'
mv torrents/'[Erai-raws] Mahouka Koukou no Rettousei - Raihousha Hen - 04 [1080p].mkv' 'Mahouka Koukou no Rettousei - Raihousha Hen'/'[Erai-raws] Mahouka Koukou no Rettousei - Raihousha Hen - 04 [1080p].mkv'
mkdir -p 'Mahouka Koukou no Rettousei - Raihousha Hen'
mv torrents/'[Erai-raws] Mahouka Koukou no Rettousei - Raihousha Hen - 04 [v0][1080p].mkv' 'Mahouka Koukou no Rettousei - Raihousha Hen'/'[Erai-raws] Mahouka Koukou no Rettousei - Raihousha Hen - 04 [v0][1080p].mkv'
mkdir -p 'Majo no Tabitabi'
mv torrents/'[Erai-raws] Majo no Tabitabi - 04 [1080p].mkv' 'Majo no Tabitabi'/'[Erai-raws] Majo no Tabitabi - 04 [1080p].mkv'
mkdir -p 'Majo no Tabitabi'
mv torrents/'[Erai-raws] Majo no Tabitabi - 04 [v0][1080p].mkv' 'Majo no Tabitabi'/'[Erai-raws] Majo no Tabitabi - 04 [v0][1080p].mkv'
mkdir -p 'Major 2nd (TV) 2nd Season'
mv torrents/'[Erai-raws] Major 2nd (TV) 2nd Season - 23 [1080p][Multiple Subtitle].mkv' 'Major 2nd (TV) 2nd Season'/'[Erai-raws] Major 2nd (TV) 2nd Season - 23 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Munou na Nana'
mv torrents/'[Erai-raws] Munou na Nana - 04 [v0][1080p].mkv' 'Munou na Nana'/'[Erai-raws] Munou na Nana - 04 [v0][1080p].mkv'
mkdir -p 'One Piece'
mv torrents/'[Erai-raws] One Piece - 947 [1080p].mkv' 'One Piece'/'[Erai-raws] One Piece - 947 [1080p].mkv'
mkdir -p 'Rail Romanesque'
mv torrents/'[Erai-raws] Rail Romanesque - 04 [1080p][Multiple Subtitle].mkv' 'Rail Romanesque'/'[Erai-raws] Rail Romanesque - 04 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Senyoku no Sigrdrifa'
mv torrents/'[Erai-raws] Senyoku no Sigrdrifa - 04 [v0][1080p].mkv' 'Senyoku no Sigrdrifa'/'[Erai-raws] Senyoku no Sigrdrifa - 04 [v0][1080p].mkv'
mkdir -p 'Taisou Zamurai'
mv torrents/'[Erai-raws] Taisou Zamurai - 03 [v0][1080p].mkv' 'Taisou Zamurai'/'[Erai-raws] Taisou Zamurai - 03 [v0][1080p].mkv'
mkdir -p 'Toji no Miko - Kizamishi Issen no Tomoshibi'
mv torrents/'[Erai-raws] Toji no Miko - Kizamishi Issen no Tomoshibi - 01 [1080p][Multiple Subtitle].mkv' 'Toji no Miko - Kizamishi Issen no Tomoshibi'/'[Erai-raws] Toji no Miko - Kizamishi Issen no Tomoshibi - 01 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Tonikaku Kawaii'
mv torrents/'[Erai-raws] Tonikaku Kawaii - 04 [1080p][Multiple Subtitle].mkv' 'Tonikaku Kawaii'/'[Erai-raws] Tonikaku Kawaii - 04 [1080p][Multiple Subtitle].mkv'
mkdir -p 'Yuukoku no Moriarty'
mv torrents/'[Erai-raws] Yuukoku no Moriarty - 03 [v0][1080p].mkv' 'Yuukoku no Moriarty'/'[Erai-raws] Yuukoku no Moriarty - 03 [v0][1080p].mkv'
